# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C8NwxzJoF4K2fQHldYXbMBPVmoJRS4jS
"""

a=float(input("enter a:"))
b=float(input("enter b:"))
op=input('enter the operation +,-,*,/')

def add(a,b):
  print(a+b)
def sub(a,b):
  print(a-b)
def mul(a,b):
  print(a*b)
def div(a,b):
  print(a/b)

if(op=='+'):
  add(a,b)
elif(op=='-'):
  sub(a,b)
elif(op=='*'):
  mul(a,b)
elif(op=='/'):
  div(a,b)
else:
  print("invalid")